name: ohftokv5
description: OHF Partners brings you the best content in the best way.
publish_to: "none" # Remove this if you plan to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  firebase_app_check: ^0.2.1+8

  # State management & dependency injection
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Environment variable management
  flutter_dotenv: ^5.1.0

  # AI and OpenAI integration
  dart_openai: ^5.0.0

  # Permissions
  permission_handler: ^10.2.0

  # Video optimization and caching
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  preload_page_view: ^0.2.0
  visibility_detector: ^0.4.0+2

  # Video player packages
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.4

  # Network monitoring
  connectivity_plus: ^6.1.3
  http: ^1.1.0

  # Speech and AI
  speech_to_text: ^7.0.0
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3
  pinecone: ^0.7.2

  # Cloud Functions
  cloud_functions: ^4.7.6

  # Image picker and file handling
  image_picker: ^1.0.7
  file_picker: ^6.1.1

  # Encryption
  crypto: ^3.0.3

  # Voice message dependencies
  record: ^5.0.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  uuid: ^4.5.1
  timeago: ^3.6.0

  # Video editing
  ffmpeg_kit_flutter: ^6.0.3

  # Camera
  camera: ^0.10.5+9

  # Gemini AI
  google_generative_ai: ^0.2.0

  # Location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3

  # WebRTC
  flutter_webrtc: ^0.9.47
  sdp_transform: ^0.3.2
  flutter_callkit_incoming: ^2.0.1+1

  # Sharing functionality
  firebase_dynamic_links: ^5.4.1
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 